"""~200 realistic, benign analytical queries used to measure the validator's false-positive rate.

Each entry is ``(sql, dialect)``; ``dialect`` is ``None`` (the generic/unknown path that
unions several sqlglot interpretations) or a Query-Builder dialect name.  Every entry must
be ACCEPTED by ``validate_sql_ast``; the suite asserts a 0% false-positive rate.
"""

from __future__ import annotations

_GENERIC: list[str] = [
    "SELECT 1",
    "SELECT 1 + 1 AS two",
    "SELECT * FROM orders",
    "SELECT id, name FROM customers WHERE id = 5",
    "SELECT id, name FROM customers WHERE name = 'O''Brien'",
    "SELECT id FROM customers WHERE note = 'a -- not a comment'",
    "SELECT id FROM customers WHERE note = 'drop table x; delete from y'",
    "SELECT id FROM customers WHERE note LIKE '%/*%'",
    "SELECT COUNT(*) FROM orders",
    "SELECT COUNT(DISTINCT customer_id) AS buyers FROM orders",
    "SELECT customer_id, SUM(amount) AS total FROM orders GROUP BY customer_id",
    "SELECT customer_id, SUM(amount) AS total FROM orders GROUP BY customer_id HAVING SUM(amount) > 1000",
    "SELECT customer_id, AVG(amount), MIN(amount), MAX(amount) FROM orders GROUP BY 1 ORDER BY 2 DESC",
    "SELECT status, COUNT(*) FROM orders GROUP BY status ORDER BY COUNT(*) DESC LIMIT 10",
    "SELECT * FROM orders ORDER BY created_at DESC LIMIT 100 OFFSET 200",
    "SELECT * FROM orders WHERE created_at >= '2024-01-01' AND created_at < '2025-01-01'",
    "SELECT * FROM orders WHERE amount BETWEEN 10 AND 100",
    "SELECT * FROM orders WHERE status IN ('open', 'closed', 'pending')",
    "SELECT * FROM orders WHERE status NOT IN ('cancelled')",
    "SELECT * FROM orders WHERE customer_id IS NOT NULL",
    "SELECT * FROM orders WHERE note IS NULL OR note = ''",
    "SELECT * FROM orders WHERE NOT (status = 'open' AND amount > 5)",
    "SELECT o.id, c.name FROM orders o JOIN customers c ON c.id = o.customer_id",
    "SELECT o.id, c.name FROM orders AS o INNER JOIN customers AS c ON c.id = o.customer_id WHERE c.region = 'EU'",
    "SELECT o.id, c.name FROM orders o LEFT JOIN customers c ON c.id = o.customer_id",
    "SELECT o.id, c.name FROM orders o LEFT OUTER JOIN customers c ON c.id = o.customer_id WHERE c.id IS NULL",
    "SELECT o.id, c.name FROM orders o RIGHT JOIN customers c ON c.id = o.customer_id",
    "SELECT o.id, c.name FROM orders o FULL OUTER JOIN customers c ON c.id = o.customer_id",
    "SELECT o.id, c.name FROM orders o CROSS JOIN customers c",
    "SELECT o.id, c.name FROM orders o, customers c WHERE c.id = o.customer_id",
    "SELECT * FROM orders o JOIN customers c USING (id)",
    "SELECT * FROM orders NATURAL JOIN customers",
    "SELECT o.id, c.name, p.title FROM orders o JOIN customers c ON c.id = o.customer_id JOIN products p ON p.id = o.product_id",
    "SELECT * FROM (SELECT customer_id, SUM(amount) AS total FROM orders GROUP BY customer_id) t WHERE t.total > 100",
    "SELECT * FROM orders WHERE customer_id IN (SELECT id FROM customers WHERE region = 'US')",
    "SELECT * FROM orders o WHERE EXISTS (SELECT 1 FROM customers c WHERE c.id = o.customer_id)",
    "SELECT * FROM orders o WHERE NOT EXISTS (SELECT 1 FROM refunds r WHERE r.order_id = o.id)",
    "SELECT id, (SELECT MAX(amount) FROM orders o WHERE o.customer_id = c.id) AS biggest FROM customers c",
    "SELECT * FROM orders WHERE amount > (SELECT AVG(amount) FROM orders)",
    "SELECT * FROM orders WHERE amount > ALL (SELECT amount FROM refunds)",
    "SELECT * FROM orders WHERE amount > ANY (SELECT amount FROM refunds)",
    "WITH recent AS (SELECT * FROM orders WHERE created_at > '2024-01-01') SELECT customer_id, COUNT(*) FROM recent GROUP BY customer_id",
    "WITH a AS (SELECT 1 AS x), b AS (SELECT x + 1 AS y FROM a) SELECT * FROM b",
    "WITH totals AS (SELECT customer_id, SUM(amount) AS s FROM orders GROUP BY 1), ranked AS (SELECT customer_id, s, RANK() OVER (ORDER BY s DESC) AS r FROM totals) SELECT * FROM ranked WHERE r <= 10",
    "WITH orders_cte AS (SELECT * FROM orders) SELECT * FROM orders_cte o JOIN customers c ON c.id = o.customer_id",
    "SELECT customer_id FROM orders UNION SELECT id FROM customers",
    "SELECT customer_id FROM orders UNION ALL SELECT id FROM customers",
    "SELECT customer_id FROM orders INTERSECT SELECT id FROM customers",
    "SELECT customer_id FROM orders EXCEPT SELECT id FROM customers",
    "(SELECT id FROM orders) UNION (SELECT id FROM customers) ORDER BY 1",
    "SELECT id, ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY created_at) AS rn FROM orders",
    "SELECT id, SUM(amount) OVER (PARTITION BY customer_id ORDER BY created_at ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running FROM orders",
    "SELECT id, LAG(amount, 1) OVER (ORDER BY created_at) AS prev, LEAD(amount) OVER (ORDER BY created_at) AS nxt FROM orders",
    "SELECT id, NTILE(4) OVER (ORDER BY amount) AS quartile FROM orders",
    "SELECT id, FIRST_VALUE(amount) OVER w, LAST_VALUE(amount) OVER w FROM orders WINDOW w AS (PARTITION BY customer_id ORDER BY created_at)",
    "SELECT id, CASE WHEN amount > 100 THEN 'big' WHEN amount > 10 THEN 'mid' ELSE 'small' END AS bucket FROM orders",
    "SELECT COALESCE(note, 'n/a') AS note, NULLIF(status, '') AS status FROM orders",
    "SELECT CAST(amount AS INTEGER) AS amt, CAST(id AS VARCHAR(20)) AS sid FROM orders",
    "SELECT UPPER(name), LOWER(name), LENGTH(name), TRIM(name), SUBSTRING(name, 1, 3) FROM customers",
    "SELECT name || ' ' || surname AS full_name FROM customers",
    "SELECT ABS(amount), ROUND(amount, 2), CEIL(amount), FLOOR(amount), amount % 7, POWER(amount, 2), SQRT(amount) FROM orders",
    "SELECT EXTRACT(YEAR FROM created_at) AS y, COUNT(*) FROM orders GROUP BY EXTRACT(YEAR FROM created_at)",
    "SELECT id FROM orders WHERE created_at > CURRENT_DATE - INTERVAL '30' DAY",
    "SELECT DATE(created_at) AS d, SUM(amount) FROM orders GROUP BY DATE(created_at) ORDER BY d",
    "SELECT status, SUM(CASE WHEN amount > 100 THEN 1 ELSE 0 END) AS big_orders FROM orders GROUP BY status",
    "SELECT status, COUNT(*) FILTER (WHERE amount > 100) AS big FROM orders GROUP BY status",
    "SELECT DISTINCT region FROM customers ORDER BY region",
    "SELECT DISTINCT ON (customer_id) customer_id, created_at FROM orders ORDER BY customer_id, created_at DESC",
    "SELECT region, COUNT(*) AS n FROM customers GROUP BY ROLLUP (region)",
    "SELECT region, status, COUNT(*) FROM customers GROUP BY CUBE (region, status)",
    "SELECT region, status, COUNT(*) FROM customers GROUP BY GROUPING SETS ((region), (status), ())",
    "SELECT * FROM orders WHERE note LIKE 'abc%' ESCAPE '\\'",
    "SELECT * FROM customers WHERE name LIKE '%smith%' OR name LIKE 'j%'",
    "SELECT * FROM customers WHERE email NOT LIKE '%@example.com'",
    "SELECT id, amount * 1.2 AS gross, amount / 3.0 AS third FROM orders",
    "SELECT id, -amount AS neg, +amount AS pos FROM orders",
    "SELECT id FROM orders WHERE (status = 'open' OR status = 'pending') AND amount > 0",
    "SELECT id FROM orders WHERE customer_id = 1 OR customer_id = 2 OR customer_id = 3",
    "SELECT o.* FROM orders o",
    'SELECT o.id AS "order id", c.name AS "Customer Name" FROM orders o JOIN customers c ON c.id = o.customer_id',
    'SELECT "id", "name" FROM "customers" WHERE "region" = \'EU\'',
    'SELECT "order", "select" FROM "table"',
    "SELECT t.* FROM (VALUES (1, 'a'), (2, 'b')) AS t (id, label)",
    "SELECT * FROM orders WHERE id = :id",
    "SELECT * FROM orders WHERE id = ? AND status = ?",
    "SELECT * FROM orders WHERE id = %s AND status = %s",
    "SELECT * FROM orders WHERE id = %(id)s",
    "SELECT * FROM orders WHERE id = $1 AND status = $2",
    "SELECT * FROM orders WHERE id = @id",
    "SELECT * FROM orders LIMIT ? OFFSET ?",
    "SELECT * FROM orders LIMIT %s OFFSET %s",
    "SELECT * FROM analytics.daily_revenue WHERE day > '2024-06-01'",
    "SELECT * FROM warehouse.sales.fact_orders",
    "SELECT * FROM sales.fact_orders f JOIN sales.dim_customer d ON d.id = f.customer_id",
    "SELECT user_id, event, ts FROM events WHERE ts >= '2024-01-01' ORDER BY ts",
    "SELECT user_id, COUNT(*) AS sessions FROM sessions GROUP BY user_id HAVING COUNT(*) > 5",
    "SELECT u.id, u.email, COUNT(o.id) AS orders FROM users u LEFT JOIN orders o ON o.user_id = u.id GROUP BY u.id, u.email",
    "SELECT users.id FROM users",
    "SELECT user_profile_id FROM profiles",
    "SELECT created_by, updated_by FROM documents",
    "SELECT a.password_changed_at FROM accounts a",
    "SELECT passwords_reset_count FROM metrics",
    "SELECT permission_count FROM roles_summary",
    "SELECT group_name, COUNT(*) FROM user_groups_report GROUP BY group_name",
    "SELECT session_count FROM web_sessions_daily",
    "SELECT * FROM auth_user_stats",
    "SELECT * FROM my_auth_users",
    "SELECT * FROM audit_log_summary WHERE action = 'login'",
    "SELECT 'auth_user' AS table_label, COUNT(*) FROM orders",
    'SELECT COUNT(*) AS "public" FROM orders',
    "SELECT sys_id, sys_created FROM tickets",
    "SELECT master_id FROM merges",
    "SELECT public_flag FROM docs WHERE public_flag = 1",
    "SELECT m.id FROM master_data m",
    "SELECT information FROM notes",
    "SELECT sleep_hours, mysql_version_label FROM health_metrics",
    "SELECT benchmark_score FROM models",
    "SELECT call_count, do_not_contact FROM leads",
    "SELECT insert_count, update_count, delete_count FROM etl_stats",
    "SELECT created_at, updated_at, deleted_at FROM orders WHERE deleted_at IS NULL",
    "SELECT lock_version, replace_count FROM docs",
    "SELECT into_count FROM funnel",
    "SELECT * FROM orders -- trailing comment",
    "SELECT * FROM orders /* block comment */ WHERE id = 1",
    "/* leading */ SELECT * FROM orders",
    "SELECT /* inline */ id FROM orders",
    "SELECT id FROM orders WHERE note = 'it''s fine' -- keep",
    "SELECT * FROM orders;",
    "SELECT * FROM orders ;  ",
    "  SELECT   *   FROM   orders  ",
    "SELECT\n  id,\n  name\nFROM\n  customers\nWHERE\n  id > 1\nORDER BY\n  name",
    "SELECT id FROM orders WHERE note = 'multi\nline'",
    "SELECT id FROM orders WHERE note = 'éè unicode 你好'",
    "SELECT café FROM menu",
    "SELECT id FROM orders WHERE amount = 1e3 OR amount = .5 OR amount = 0.25",
    "SELECT id FROM orders WHERE flag = TRUE AND other = FALSE",
    "SELECT MAX(amount) - MIN(amount) AS spread FROM orders",
    "SELECT SUM(amount) / NULLIF(COUNT(*), 0) AS avg_order FROM orders",
    "SELECT STDDEV(amount), VARIANCE(amount) FROM orders",
    "SELECT PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY amount) AS median FROM orders",
    "SELECT MODE() WITHIN GROUP (ORDER BY status) FROM orders",
    "SELECT customer_id, ARRAY_AGG(id) FROM orders GROUP BY customer_id",
    "SELECT customer_id, STRING_AGG(status, ',') FROM orders GROUP BY customer_id",
    "SELECT customer_id, GROUP_CONCAT(status) FROM orders GROUP BY customer_id",
    "SELECT COUNT(*) OVER () AS total, id FROM orders",
    "SELECT id FROM orders FETCH FIRST 10 ROWS ONLY",
    "SELECT id FROM orders ORDER BY id OFFSET 5 ROWS FETCH NEXT 10 ROWS ONLY",
    "SELECT id FROM orders ORDER BY amount DESC NULLS LAST",
    "SELECT id FROM orders ORDER BY amount ASC NULLS FIRST, id",
    "SELECT t.a FROM (SELECT 1 AS a) t",
    "SELECT * FROM ((SELECT 1 AS a) UNION ALL (SELECT 2)) u",
    "SELECT * FROM (SELECT * FROM (SELECT * FROM orders) a) b",
    "SELECT * FROM orders o1 JOIN orders o2 ON o1.customer_id = o2.customer_id AND o1.id < o2.id",
    "SELECT a.id FROM orders a JOIN orders b ON a.id = b.id JOIN orders c ON b.id = c.id JOIN orders d ON c.id = d.id",
    "SELECT * FROM orders WHERE id IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)",
    "SELECT * FROM orders WHERE (customer_id, product_id) IN ((1, 2), (3, 4))",
    "SELECT * FROM orders WHERE amount >= 10 AND amount <= 20 OR amount = 0",
    "SELECT id, amount, amount / SUM(amount) OVER () AS share FROM orders",
    "SELECT id FROM orders WHERE created_at IS NOT NULL ORDER BY created_at LIMIT 1",
    "SELECT * FROM orders WHERE LOWER(status) = 'open'",
    "SELECT * FROM orders WHERE status = 'open' AND (region = 'EU' OR region = 'US')",
    "SELECT product_id, SUM(quantity * price) AS revenue FROM order_items GROUP BY product_id ORDER BY revenue DESC LIMIT 20",
    "SELECT c.region, p.category, SUM(oi.quantity * oi.price) AS revenue FROM order_items oi JOIN orders o ON o.id = oi.order_id JOIN customers c ON c.id = o.customer_id JOIN products p ON p.id = oi.product_id GROUP BY c.region, p.category",
    "SELECT d.name, COUNT(e.id) AS headcount, AVG(e.salary) AS avg_salary FROM departments d LEFT JOIN employees e ON e.department_id = d.id GROUP BY d.name HAVING COUNT(e.id) > 3",
    "SELECT e.name, m.name AS manager FROM employees e LEFT JOIN employees m ON m.id = e.manager_id",
    "SELECT * FROM employees WHERE salary > (SELECT AVG(salary) FROM employees WHERE department_id = employees.department_id)",
    "SELECT department_id, MAX(salary) FROM employees GROUP BY department_id",
    "SELECT name FROM employees WHERE hire_date < '2020-01-01' AND termination_date IS NULL",
    "SELECT month, revenue, revenue - LAG(revenue) OVER (ORDER BY month) AS delta FROM monthly_revenue",
    "SELECT cohort, SUM(CASE WHEN week = 0 THEN 1 ELSE 0 END) AS w0, SUM(CASE WHEN week = 1 THEN 1 ELSE 0 END) AS w1 FROM retention GROUP BY cohort",
    "SELECT page, COUNT(DISTINCT visitor_id) AS uniques FROM pageviews WHERE ts > '2024-05-01' GROUP BY page ORDER BY uniques DESC",
    "SELECT campaign, SUM(spend) AS spend, SUM(conversions) AS conv, SUM(spend) / NULLIF(SUM(conversions), 0) AS cpa FROM ads GROUP BY campaign",
    "SELECT sensor_id, AVG(temp) AS avg_temp FROM readings WHERE ts BETWEEN '2024-01-01' AND '2024-01-31' GROUP BY sensor_id",
    "SELECT ticker, close, AVG(close) OVER (PARTITION BY ticker ORDER BY day ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ma7 FROM prices",
    "SELECT * FROM inventory WHERE quantity < reorder_level ORDER BY quantity",
    "SELECT a.account_id, SUM(t.amount) AS balance FROM accounts a JOIN transactions t ON t.account_id = a.account_id GROUP BY a.account_id",
    "SELECT patient_id, MIN(visit_date) AS first_visit, MAX(visit_date) AS last_visit, COUNT(*) AS visits FROM visits GROUP BY patient_id",
    "SELECT course_id, AVG(score) AS mean, MIN(score), MAX(score) FROM grades GROUP BY course_id",
    "SELECT country, COUNT(*) FROM users WHERE signup_date >= '2024-01-01' GROUP BY country ORDER BY 2 DESC LIMIT 5",
]

# Dialect-specific benign queries (dialect, sql).
_DIALECT: list[tuple[str, str]] = [
    ("postgres", "SELECT id::text, created_at::date FROM orders"),
    (
        "postgres",
        "SELECT date_trunc('month', created_at) AS m, COUNT(*) FROM orders GROUP BY 1",
    ),
    ("postgres", "SELECT * FROM orders WHERE tags @> ARRAY['a']"),
    ("postgres", "SELECT payload->>'name' AS name, payload->'a'->>'b' FROM events"),
    ("postgres", "SELECT * FROM generate_series(1, 10) AS g(n)"),
    ("postgres", "SELECT * FROM unnest(ARRAY[1,2,3]) AS u(x)"),
    (
        "postgres",
        "SELECT o.id, l.* FROM orders o, LATERAL (SELECT * FROM lines WHERE order_id = o.id LIMIT 3) l",
    ),
    ("postgres", "SELECT * FROM orders WHERE created_at > now() - interval '7 days'"),
    (
        "postgres",
        "SELECT to_char(created_at, 'YYYY-MM') AS ym, SUM(amount) FROM orders GROUP BY 1",
    ),
    ("postgres", "SELECT * FROM orders WHERE note ~ '^abc' AND note !~ 'x$'"),
    ("postgres", "SELECT * FROM orders WHERE note ILIKE '%abc%'"),
    ("postgres", "SELECT id, jsonb_array_length(items) FROM carts"),
    ("postgres", "SELECT * FROM orders FETCH FIRST 5 ROWS ONLY"),
    ("mysql", "SELECT `id`, `name` FROM `customers` WHERE `region` = 'EU'"),
    ("mysql", "SELECT * FROM `orders` LIMIT 10, 20"),
    (
        "mysql",
        "SELECT DATE_FORMAT(created_at, '%Y-%m') AS ym, COUNT(*) FROM orders GROUP BY ym",
    ),
    ("mysql", "SELECT IFNULL(note, '') FROM orders"),
    (
        "mysql",
        "SELECT customer_id, GROUP_CONCAT(status SEPARATOR ',') FROM orders GROUP BY customer_id",
    ),
    ("mysql", "SELECT * FROM orders WHERE created_at > NOW() - INTERVAL 7 DAY"),
    ("mysql", "SELECT * FROM orders USE INDEX (idx_a) WHERE id = 1"),
    ("mysql", "SELECT JSON_EXTRACT(payload, '$.a') FROM events"),
    (
        "mysql",
        "SELECT * FROM orders WHERE MATCH(note) AGAINST ('foo' IN NATURAL LANGUAGE MODE)",
    ),
    (
        "sqlite",
        "SELECT strftime('%Y-%m', created_at) AS ym, COUNT(*) FROM orders GROUP BY 1",
    ),
    ("sqlite", "SELECT id, ifnull(note, '') FROM orders LIMIT 5"),
    ("sqlite", "SELECT json_extract(payload, '$.a') FROM events"),
    ("sqlite", "SELECT * FROM orders WHERE note GLOB 'a*'"),
    ("sqlite", "SELECT typeof(amount), total(amount) FROM orders"),
    ("sqlite", "SELECT * FROM orders ORDER BY random() LIMIT 3"),
    ("tsql", "SELECT TOP 10 * FROM orders"),
    ("tsql", "SELECT [id], [name] FROM [customers] WHERE [region] = 'EU'"),
    ("tsql", "SELECT id FROM orders ORDER BY id OFFSET 10 ROWS FETCH NEXT 5 ROWS ONLY"),
    ("tsql", "SELECT ISNULL(note, '') AS note, GETDATE() AS now FROM orders"),
    (
        "tsql",
        "SELECT DATEPART(year, created_at) AS y, COUNT(*) FROM orders GROUP BY DATEPART(year, created_at)",
    ),
    ("tsql", "SELECT * FROM dbo.orders o WITH (NOLOCK) WHERE o.id = 1"),
    ("tsql", "SELECT CONVERT(varchar(10), created_at, 120) FROM orders"),
    (
        "bigquery",
        "SELECT * FROM `proj.dataset.orders` WHERE DATE(created_at) = '2024-01-01'",
    ),
    ("bigquery", "SELECT SAFE_DIVIDE(a, b) AS r, DATE_TRUNC(d, MONTH) FROM t"),
    ("bigquery", "SELECT x FROM UNNEST([1, 2, 3]) AS x"),
    ("bigquery", "SELECT * EXCEPT (secret) FROM orders"),
    ("bigquery", "SELECT ARRAY_AGG(id ORDER BY created_at LIMIT 3) FROM orders"),
    (
        "snowflake",
        "SELECT * FROM orders QUALIFY ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY created_at DESC) = 1",
    ),
    ("snowflake", "SELECT payload:name::string AS name FROM events"),
    ("snowflake", "SELECT DATEADD(day, -7, CURRENT_DATE()) AS d"),
    ("snowflake", "SELECT * FROM TABLE(FLATTEN(input => PARSE_JSON('[1,2]')))"),
    (
        "clickhouse",
        "SELECT toStartOfMonth(created_at) AS m, count() FROM orders GROUP BY m",
    ),
    ("clickhouse", "SELECT * FROM orders FINAL WHERE id = 1"),
    ("clickhouse", "SELECT uniqExact(customer_id) FROM orders"),
    ("clickhouse", "SELECT * FROM orders LIMIT 10 SETTINGS max_threads = 2"),
    ("oracle", "SELECT * FROM orders WHERE ROWNUM <= 10"),
    ("oracle", "SELECT NVL(note, 'n/a') FROM orders"),
    ("oracle", "SELECT TO_CHAR(created_at, 'YYYY-MM') FROM orders"),
    ("oracle", "SELECT * FROM orders FETCH FIRST 10 ROWS ONLY"),
    ("oracle", "SELECT id FROM dual"),
    ("duckdb", "SELECT * FROM orders USING SAMPLE 10%"),
    ("duckdb", "SELECT list_sum([1,2,3]) AS s"),
    ("duckdb", "SELECT * EXCLUDE (secret) FROM orders"),
    ("duckdb", "SELECT customer_id, SUM(amount) FROM orders GROUP BY ALL"),
    ("redshift", "SELECT * FROM orders WHERE created_at > DATEADD(day, -7, GETDATE())"),
    ("databricks", "SELECT * FROM main.sales.orders WHERE ds = '2024-01-01'"),
    ("spark", "SELECT * FROM orders DISTRIBUTE BY customer_id"),
    ("trino", "SELECT * FROM hive.sales.orders WHERE ds = DATE '2024-01-01'"),
    ("hive", "SELECT * FROM orders LATERAL VIEW EXPLODE(tags) t AS tag"),
]

BENIGN_CORPUS: list[tuple[str, str | None]] = [(s, None) for s in _GENERIC] + [
    (s, d) for d, s in _DIALECT
]
